# Generated by Django 5.2.16 on 2026-07-20 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name': 'author', 'verbose_name_plural': 'authors'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='readinglistitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'saved book', 'verbose_name_plural': 'saved books'},
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, help_text='Optional. Shown on the author page.', verbose_name='short bio'),
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200, verbose_name='display name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(help_text='Used in the author page URL. Auto-filled from the name.', unique=True, verbose_name='URL slug'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text='Hold Ctrl (Windows) or Cmd (Mac) to select more than one.', related_name='books', to='catalog.author', verbose_name='authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalog.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, help_text='Full https:// link to a cover image (Unsplash, CDN, etc.).', verbose_name='cover image URL'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(help_text='Main blurb on the book page. Keep it clear for readers.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Turn on to show this book in the Featured section of the home page.', verbose_name='featured on home page'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, help_text='Optional. Format: YYYY-MM-DD.', null=True, verbose_name='publication date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(help_text='Auto-filled from the title. Appears in /books/your-slug/.', unique=True, verbose_name='URL slug'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Used in filters and URLs. Auto-filled from the name.', unique=True, verbose_name='URL slug'),
        ),
        migrations.AlterField(
            model_name='readinglistitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_shelves', to='catalog.book', verbose_name='book'),
        ),
        migrations.AlterField(
            model_name='readinglistitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='saved on'),
        ),
        migrations.AlterField(
            model_name='readinglistitem',
            name='notes',
            field=models.CharField(blank=True, help_text='Optional note from or about this saved book.', max_length=255, verbose_name='private note'),
        ),
        migrations.AlterField(
            model_name='readinglistitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_list', to=settings.AUTH_USER_MODEL, verbose_name='reader'),
        ),
    ]
