# Generated by Django 5.2.16 on 2026-07-20 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_labels_pt_leigos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_books', models.BooleanField(default=True, help_text='Add, edit, and delete books.', verbose_name='Books')),
                ('can_manage_authors', models.BooleanField(default=True, help_text='Add, edit, and delete authors.', verbose_name='Authors')),
                ('can_manage_categories', models.BooleanField(default=True, help_text='Add, edit, and delete categories.', verbose_name='Categories')),
                ('can_view_saved', models.BooleanField(default=True, help_text='See which books readers saved.', verbose_name='Saved by readers')),
                ('can_manage_team', models.BooleanField(default=False, help_text='Add other admins and change what they can access.', verbose_name='Team & permissions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'staff access',
                'verbose_name_plural': 'staff access',
            },
        ),
    ]
